# Generated by Django 3.2.12 on 2025-03-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenniCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodina_start', models.DateField()),
                ('hodina_konec', models.DateField()),
                ('naviseni_ceny', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hriste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=50)),
                ('popis', models.TextField()),
                ('cena_hodina', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kapacita', models.IntegerField()),
                ('aktivni', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SezoniCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesic_start', models.DateField()),
                ('mesic_konec', models.DateField()),
                ('naviseni_ceny', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypZakaznika',
            fields=[
                ('typ_zakaznika', models.CharField(choices=[('new', 'New'), ('long_term', 'Long Term'), ('vip', 'VIP')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sleva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapujcky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('cena_pujceni', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cena_prodeje', models.DecimalField(decimal_places=2, max_digits=8)),
                ('typ', models.CharField(choices=[('pujcka', 'Půjčka'), ('prodej', 'Prodej'), ('oboji', 'Obojí')], max_length=20)),
                ('aktivni', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('datum_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('posledni_aktualizace', models.DateTimeField(auto_now=True)),
                ('typ_zakaznika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzivatele', to='rezervace.typzakaznika')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uzivatele', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('cas_zacatku', models.TimeField()),
                ('cas_konce', models.TimeField()),
                ('stav', models.CharField(choices=[('nova', 'Nova'), ('potvrzena', 'Potvrzena'), ('zrusena', 'Zrušena')], default='nova', max_length=20)),
                ('popis', models.TextField(blank=True, null=True)),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now)),
                ('naposledy_upraveno', models.DateTimeField(auto_now=True)),
                ('cena', models.FloatField()),
                ('hriste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervace', to='rezervace.hriste')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervace', to='rezervace.uzivatele')),
            ],
        ),
        migrations.CreateModel(
            name='Novinky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now)),
                ('zverejneno', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novinky', to='rezervace.uzivatele')),
            ],
        ),
        migrations.CreateModel(
            name='RezervaceZapujcky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField()),
                ('cena_za_kus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rezervace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapujcky', to='rezervace.rezervace')),
                ('zapujcka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervace', to='rezervace.zapujcky')),
            ],
            options={
                'unique_together': {('rezervace', 'zapujcka')},
            },
        ),
    ]
